# ???????????
spring:
  datasource:
    url: jdbc:sqlite:./data/meta.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
# ?? Mybatis ? xml ????
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration: # ???? MyBatis ??? SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# ???? MyBatis ??? SQL
logging:
  level:
    com:
      example:
        demo: debug